Script di generazione ambassadors
Il-Libro-Open-Source/governance pull request #15
Opened 2023-10-02 19:03 UTC by eppak

2023-10-03 07:02 UTC, corradopetrelli requested changes
Grazie mille Alessandro 😃 Una piccola modifica migliorativa e ci siamo!

2023-10-03 07:02 UTC, corradopetrelli commented on ambassadors.js
> +        console.log(`-[${user.name}](${user.url}) - (${user.date} - Attualmente in carica)`);
Correlato al ragionamento fatto nel commetto del file `ambassadors_list.json`  proporrei qualcosa del tipo:

```javascript
console.log(`-[${user.name}](${user.url}) - (${user.beginDate} - ${user.endDate ?? "Attualmente in carica"})`);
```

2023-10-03 07:19 UTC, Cadienvan commented
Mi torna ciò che dice Corrado, ha senso in ottica futua.

2023-10-03 18:30 UTC, eppak commented on ambassadors.js
> +        console.log(`-[${user.name}](${user.url}) - (${user.date} - Attualmente in carica)`);
Fatta modifica come da indicazione

2023-10-03 18:30 UTC, eppak commented on ambassadors_list.json
> +    },
Fatta modifica

2023-10-03 19:07 UTC, corradopetrelli requested changes
Mancano 4 persone. Mi risultano qui 36 elementi nel json ma siamo in 40 sul gruppo telegram.

2023-10-03 19:07 UTC, corradopetrelli commented on ambassadors_list.json
> +        "beginDate": "2023-09-05"
```suggestion
        "beginDate": "2023-09-05",
        "endDate": null
```

2023-10-04 07:38 UTC, Cadienvan approved these changes

2023-10-04 07:40 UTC, corradopetrelli approved these changes

2023-10-04 14:23 UTC, guizzo approved these changes
LGTM

2023-10-04 14:35 UTC, merged