Aggiunta minuta discussion group
Il-Libro-Open-Source/governance pull request #40
Opened 2023-10-27 17:13 UTC by JeyDi

Note e commenti della discussione di oggi 27.10.2023

2023-10-27 19:38 UTC, guizzo requested changes
Giusto un typo, per il resto LGTM

2023-10-27 19:38 UTC, guizzo commented on meetings/2023-10-27-Discussion.md
> +Prendere il mano il task FAQ e domande frequenti in generale.
```suggestion
Prendere in mano il task FAQ e domande frequenti in generale.
```

2023-10-28 07:30 UTC, Cadienvan approved these changes

2023-10-28 07:39 UTC, eppak approved these changes

2023-10-28 08:09 UTC, merged